import { CanvasBoardState, KnowledgeObjectType } from '../types/canvas';

export const OBJECT_TYPE_SUGGESTIONS: Record<string, { label: string; key: string; defaultValue: string }[]> = {
  '': [
    { label: 'Status', key: 'Status', defaultValue: 'Active' },
    { label: 'Owner', key: 'Owner', defaultValue: 'Team' },
  ],
  Generic: [
    { label: 'Status', key: 'Status', defaultValue: 'Active' },
    { label: 'Owner', key: 'Owner', defaultValue: 'Team' },
  ],
  Microservice: [
    { label: 'Language', key: 'Language', defaultValue: 'TypeScript / Go' },
    { label: 'Status', key: 'Status', defaultValue: 'Production' },
    { label: 'Version', key: 'Version', defaultValue: 'v2.4.0' },
    { label: 'Repository', key: 'Repo', defaultValue: 'github.com/org/service' },
    { label: 'Owner', key: 'Owner', defaultValue: 'Core Engineering' },
  ],
  Database: [
    { label: 'Engine', key: 'Engine', defaultValue: 'PostgreSQL 16' },
    { label: 'Capacity', key: 'Capacity', defaultValue: '500 GB' },
    { label: 'Replication', key: 'Replication', defaultValue: 'Multi-AZ Sync' },
    { label: 'Port', key: 'Port', defaultValue: '5432' },
  ],
  Person: [
    { label: 'Role', key: 'Role', defaultValue: 'Staff Architect' },
    { label: 'Team', key: 'Team', defaultValue: 'Infrastructure' },
    { label: 'Email', key: 'Email', defaultValue: 'alex@company.com' },
  ],
  Project: [
    { label: 'Phase', key: 'Phase', defaultValue: 'Beta Rollout' },
    { label: 'Target Date', key: 'Target Date', defaultValue: 'Q3 2026' },
    { label: 'Lead', key: 'Lead', defaultValue: 'DevOps Team' },
  ],
  Task: [
    { label: 'Status', key: 'Status', defaultValue: 'In Progress' },
    { label: 'Priority', key: 'Priority', defaultValue: 'High' },
    { label: 'Assignee', key: 'Assignee', defaultValue: 'Sarah M.' },
    { label: 'Due Date', key: 'Due Date', defaultValue: '2026-08-15' },
  ],
  Event: [
    { label: 'Date', key: 'Date', defaultValue: '2026-08-01' },
    { label: 'Location', key: 'Location', defaultValue: 'Zoom / SF HQ' },
  ],
  Document: [
    { label: 'Type', key: 'Doc Type', defaultValue: 'Architecture RFC' },
    { label: 'Status', key: 'Status', defaultValue: 'Approved' },
  ],
  Idea: [
    { label: 'Impact', key: 'Impact', defaultValue: 'High' },
    { label: 'Feasibility', key: 'Feasibility', defaultValue: 'Medium' },
  ],
  Device: [
    { label: 'IP Address', key: 'IP', defaultValue: '10.0.4.12' },
    { label: 'OS', key: 'OS', defaultValue: 'Ubuntu 24.04 LTS' },
  ],
  Custom: [
    { label: 'Custom Property', key: 'Property', defaultValue: 'Value' },
  ],
};

export const COLOR_PALETTE = [
  { name: 'Slate', fill: '#f8fafc', stroke: '#64748b', text: '#0f172a' },
  { name: 'Indigo', fill: '#eef2ff', stroke: '#6366f1', text: '#1e1b4b' },
  { name: 'Emerald', fill: '#ecfdf5', stroke: '#10b981', text: '#064e3b' },
  { name: 'Amber', fill: '#fffbeb', stroke: '#f59e0b', text: '#78350f' },
  { name: 'Rose', fill: '#fff1f2', stroke: '#f43f5e', text: '#881337' },
  { name: 'Sky', fill: '#f0f9ff', stroke: '#0ea5e9', text: '#0c4a6e' },
  { name: 'Purple', fill: '#faf5ff', stroke: '#a855f7', text: '#581c87' },
  { name: 'Dark Slate', fill: '#1e293b', stroke: '#475569', text: '#f8fafc' },
];

export const STICKY_COLORS = [
  { name: 'Yellow', bg: '#fef08a', text: '#713f12', border: '#fde047' },
  { name: 'Green', bg: '#bbf7d0', text: '#14532d', border: '#86efac' },
  { name: 'Blue', bg: '#bfdbfe', text: '#1e3a8a', border: '#93c5fd' },
  { name: 'Pink', bg: '#fbcfe8', text: '#831843', border: '#f9a8d4' },
  { name: 'Orange', bg: '#fed7aa', text: '#7c2d12', border: '#fdba74' },
  { name: 'Purple', bg: '#e9d5ff', text: '#581c87', border: '#d8b4fe' },
];

export const DEMO_BOARD_STATE: CanvasBoardState = {
  id: 'living-canvas-demo',
  name: 'E-Commerce System Knowledge Board',
  updatedAt: new Date().toISOString(),
  globalDisplayMode: 'compact',
  snapToGrid: true,
  showGrid: true,
  viewport: { x: 80, y: 60, zoom: 0.9 },
  elements: {
    'frame-backend': {
      id: 'frame-backend',
      type: 'frame',
      x: 320,
      y: 120,
      width: 680,
      height: 480,
      zIndex: 1,
      title: 'BACKEND SERVICES CLUSTER',
      description: 'Core microservices handling user traffic, payment, and order processing',
      objectType: 'Project',
      tags: ['backend', 'cloud-run', 'microservices'],
      style: {
        fillColor: 'rgba(241, 245, 249, 0.4)',
        strokeColor: '#94a3b8',
        strokeWidth: 2,
        strokeStyle: 'dashed',
        textColor: '#334155',
        fontSize: 14,
        fontWeight: 'bold',
        cornerRadius: 16,
      },
      properties: [
        { id: 'p1', key: 'Region', value: 'us-central1' },
        { id: 'p2', key: 'Kubernetes', value: 'v1.30-gke' },
      ],
      notes: [],
      comments: [],
      attachments: [],
      history: [
        { id: 'h1', action: 'Created', details: 'Added Frame for Backend Services', timestamp: '2026-07-24 10:00' },
      ],
    },

    'node-client': {
      id: 'node-client',
      type: 'rounded-rectangle',
      x: 60,
      y: 280,
      width: 180,
      height: 110,
      zIndex: 10,
      title: 'Web & Mobile Client',
      description: 'Next.js 15 PWA and iOS/Android Native App targeting retail customers.',
      objectType: 'Generic',
      icon: 'Smartphone',
      tags: ['frontend', 'react', 'mobile'],
      style: {
        fillColor: '#eff6ff',
        strokeColor: '#3b82f6',
        strokeWidth: 2,
        textColor: '#1e3a8a',
        fontSize: 15,
        fontWeight: 'bold',
        cornerRadius: 12,
        shadow: 'md',
      },
      properties: [
        { id: 'cp1', key: 'Framework', value: 'React 19 / Vite' },
        { id: 'cp2', key: 'DAU', value: '45,000 users/day' },
      ],
      notes: [
        {
          id: 'cn1',
          title: 'Performance Roadmap',
          content: '### Goals\n- Keep bundle size under 150KB gzip\n- Optimize LCP image loads\n- Support offline sync via IndexedDB',
          createdAt: '2026-07-20 14:20',
          updatedAt: '2026-07-22 09:15',
        },
      ],
      comments: [
        {
          id: 'cc1',
          author: 'Elena Vance',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop',
          content: 'Should we add WebSocket live cart updates in the next sprint?',
          createdAt: '2026-07-23 11:00',
        },
      ],
      attachments: [
        {
          id: 'ca1',
          name: 'Figma UI Design Specs',
          type: 'url',
          url: 'https://figma.com/file/sample-ecommerce-ui',
          uploadedAt: '2026-07-21',
        },
      ],
      history: [
        { id: 'ch1', action: 'Created', details: 'Added Client node', timestamp: '2026-07-20 10:00' },
      ],
    },

    'node-api': {
      id: 'node-api',
      type: 'rounded-rectangle',
      x: 360,
      y: 280,
      width: 190,
      height: 120,
      zIndex: 10,
      frameId: 'frame-backend',
      title: 'API Gateway',
      description: 'Envoy-based API Gateway handling JWT validation, rate limiting, and routing.',
      objectType: 'Microservice',
      icon: 'Shield',
      tags: ['gateway', 'security', 'go'],
      style: {
        fillColor: '#f0fdf4',
        strokeColor: '#22c55e',
        strokeWidth: 2,
        textColor: '#14532d',
        fontSize: 15,
        fontWeight: 'bold',
        cornerRadius: 12,
        shadow: 'md',
      },
      properties: [
        { id: 'ap1', key: 'Language', value: 'Go 1.22' },
        { id: 'ap2', key: 'Rate Limit', value: '1000 req/sec' },
        { id: 'ap3', key: 'Auth', value: 'OAuth2 / JWT' },
      ],
      notes: [
        {
          id: 'an1',
          title: 'Security Policies',
          content: 'Strict CORS policies enabled. All incoming requests require signed JWT headers.',
          createdAt: '2026-07-21 16:00',
          updatedAt: '2026-07-21 16:00',
        },
      ],
      comments: [],
      attachments: [],
      history: [],
    },

    'node-booking': {
      id: 'node-booking',
      type: 'rounded-rectangle',
      x: 630,
      y: 190,
      width: 210,
      height: 130,
      zIndex: 10,
      frameId: 'frame-backend',
      title: 'Booking Service',
      description: 'Manages order reservations, availability locks, and inventory checks.',
      objectType: 'Microservice',
      icon: 'Server',
      tags: ['microservice', 'go', 'core'],
      style: {
        fillColor: '#fefce8',
        strokeColor: '#eab308',
        strokeWidth: 2,
        textColor: '#713f12',
        fontSize: 15,
        fontWeight: 'bold',
        cornerRadius: 12,
        shadow: 'md',
      },
      properties: [
        { id: 'bp1', key: 'Language', value: 'Go 1.22' },
        { id: 'bp2', key: 'Status', value: 'Active' },
        { id: 'bp3', key: 'Replicas', value: '3 Pods' },
        { id: 'bp4', key: 'Owner', value: 'Checkout Squad' },
      ],
      notes: [
        {
          id: 'bn1',
          title: 'Distributed Lock Strategy',
          content: 'Uses Redis Redlock algorithm to lock items during 10-minute checkout windows.',
          createdAt: '2026-07-22 10:15',
          updatedAt: '2026-07-22 10:15',
        },
      ],
      comments: [
        {
          id: 'bc1',
          author: 'David Chen',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop',
          content: 'Consumer lag spikes under peak 5PM traffic. Investigating Kafka partition sizing.',
          createdAt: '2026-07-23 15:40',
        },
      ],
      attachments: [],
      history: [],
    },

    'node-kafka': {
      id: 'node-kafka',
      type: 'ellipse',
      x: 640,
      y: 390,
      width: 190,
      height: 110,
      zIndex: 10,
      frameId: 'frame-backend',
      title: 'Kafka Event Bus',
      description: 'Distributed event streaming platform for async order events and notifications.',
      objectType: 'Device',
      icon: 'Zap',
      tags: ['event-bus', 'infrastructure', 'kafka'],
      style: {
        fillColor: '#faf5ff',
        strokeColor: '#a855f7',
        strokeWidth: 2,
        textColor: '#581c87',
        fontSize: 14,
        fontWeight: 'bold',
        cornerRadius: 50,
        shadow: 'md',
      },
      properties: [
        { id: 'kp1', key: 'Type', value: 'Message Broker' },
        { id: 'kp2', key: 'Brokers', value: '3 Confluent Nodes' },
        { id: 'kp3', key: 'Retention', value: '7 Days' },
      ],
      notes: [],
      comments: [],
      attachments: [],
      history: [],
    },

    'node-db': {
      id: 'node-db',
      type: 'circle',
      x: 1080,
      y: 210,
      width: 160,
      height: 160,
      zIndex: 10,
      title: 'PostgreSQL DB',
      description: 'Primary ACID relational database for user orders and inventory balances.',
      objectType: 'Database',
      icon: 'Database',
      tags: ['database', 'postgres', 'sql'],
      style: {
        fillColor: '#ecfdf5',
        strokeColor: '#10b981',
        strokeWidth: 2,
        textColor: '#064e3b',
        fontSize: 14,
        fontWeight: 'bold',
        cornerRadius: 80,
        shadow: 'md',
      },
      properties: [
        { id: 'dp1', key: 'Engine', value: 'PostgreSQL 16' },
        { id: 'dp2', key: 'Primary', value: 'cloud-db-master-01' },
        { id: 'dp3', key: 'Connections', value: 'Max 250' },
      ],
      notes: [
        {
          id: 'dn1',
          title: 'Schema Migration RFC',
          content: '- Added indexing on `order_id` and `customer_uuid`.\n- Partitioning `orders` table by monthly range.',
          createdAt: '2026-07-22 18:00',
          updatedAt: '2026-07-22 18:00',
        },
      ],
      comments: [],
      attachments: [],
      history: [],
    },

    'sticky-architecture-note': {
      id: 'sticky-architecture-note',
      type: 'sticky-note',
      x: 60,
      y: 430,
      width: 200,
      height: 180,
      zIndex: 5,
      title: '💡 Key Architectural Principle',
      description: 'Start simple! Every shape here can be enriched with properties, markdown notes, files, and comments without disturbing canvas location.',
      objectType: 'Idea',
      tags: ['note', 'guidelines'],
      style: {
        stickyColor: '#fef08a',
        textColor: '#713f12',
        fontSize: 13,
        shadow: 'md',
      },
      properties: [],
      notes: [],
      comments: [],
      attachments: [],
      history: [],
    },
  },

  connections: {
    'conn-client-api': {
      id: 'conn-client-api',
      sourceId: 'node-client',
      targetId: 'node-api',
      sourceAnchor: 'right',
      targetAnchor: 'left',
      label: 'HTTPS / REST API',
      connectionType: 'HTTP',
      description: 'Client app sends GraphQL & REST payloads over TLS 1.3.',
      isBiDirectional: false,
      style: {
        strokeColor: '#3b82f6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        lineCurve: 'curved',
        textColor: '#1e40af',
      },
      properties: [
        { id: 'cp1', key: 'Protocol', value: 'HTTPS / HTTP2' },
        { id: 'cp2', key: 'Latency', value: '~24ms' },
      ],
      comments: [],
    },

    'conn-api-booking': {
      id: 'conn-api-booking',
      sourceId: 'node-api',
      targetId: 'node-booking',
      sourceAnchor: 'right',
      targetAnchor: 'left',
      label: 'POST /v1/orders',
      connectionType: 'HTTP',
      description: 'Proxies booking creation request with customer auth context.',
      isBiDirectional: false,
      style: {
        strokeColor: '#22c55e',
        strokeWidth: 2,
        strokeStyle: 'solid',
        lineCurve: 'orthogonal',
        textColor: '#15803d',
      },
      properties: [],
      comments: [],
    },

    'conn-booking-kafka': {
      id: 'conn-booking-kafka',
      sourceId: 'node-booking',
      targetId: 'node-kafka',
      sourceAnchor: 'bottom',
      targetAnchor: 'top',
      label: 'Publish OrderCreated',
      connectionType: 'Event',
      description: 'Emits asynchronous order lifecycle events to Kafka topic order.events.v1',
      isBiDirectional: false,
      style: {
        strokeColor: '#a855f7',
        strokeWidth: 2,
        strokeStyle: 'dashed',
        lineCurve: 'curved',
        textColor: '#6b21a8',
      },
      properties: [
        { id: 'kp1', key: 'Topic', value: 'order.events.v1' },
      ],
      comments: [],
    },

    'conn-booking-db': {
      id: 'conn-booking-db',
      sourceId: 'node-booking',
      targetId: 'node-db',
      sourceAnchor: 'right',
      targetAnchor: 'left',
      label: 'Read/Write SQL',
      connectionType: 'Data Flow',
      description: 'ACID transaction persist on PostgreSQL database.',
      isBiDirectional: true,
      style: {
        strokeColor: '#10b981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        lineCurve: 'curved',
        textColor: '#047857',
      },
      properties: [],
      comments: [],
    },
  },
};
